#!/bin/bash
# Live Accident Zone Tracking System - Command Cheat Sheet
# Copy-paste friendly commands for quick access

echo "================================"
echo "LIVE TRACKING SYSTEM - CHEAT SHEET"
echo "================================"
echo ""

# ============================================================================
# SETUP & INITIALIZATION
# ============================================================================
echo "═══════════════════════════════════════════════════════════════════════"
echo "STEP 1: SETUP & INITIALIZATION"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Navigate to project:"
echo "  cd c:\\Users\\Archana\\final_one\\LogiMetrics"
echo ""
echo "Install backend dependencies (if needed):"
echo "  cd backend && npm install socket.io && cd .."
echo ""
echo "Start backend server:"
echo "  cd backend && npm start"
echo ""
echo "Seed accident zones (in another terminal):"
echo "  cd backend && node scripts/seed-accident-zones.js"
echo ""
echo "Start frontend (in another terminal):"
echo "  cd frontend\\logimatrix-app && npm run dev"
echo ""
echo "Visit map:"
echo "  http://localhost:5173/accidents"
echo ""

# ============================================================================
# VEHICLE SIMULATORS
# ============================================================================
echo "═══════════════════════════════════════════════════════════════════════"
echo "STEP 2: VEHICLE TRACKING SIMULATORS"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Basic simulator (random movement):"
echo "  cd backend && node scripts/tracking-simulator.js --vehicle=TRUCK001"
echo ""
echo "Simulator with custom speed:"
echo "  cd backend && node scripts/tracking-simulator.js --vehicle=TRUCK001 --speed=80"
echo ""
echo "Simulator at specific location:"
echo "  cd backend && node scripts/tracking-simulator.js --vehicle=TRUCK001 --lat=18.58 --lng=73.91"
echo ""
echo "Simulator with predefined route (downtown→airport):"
echo "  cd backend && node scripts/tracking-simulator.js --vehicle=TRUCK001 --route=downtown_to_airport"
echo ""
echo "Simulator with predefined route (airport→downtown):"
echo "  cd backend && node scripts/tracking-simulator.js --vehicle=TRUCK002 --route=airport_to_downtown"
echo ""
echo "Simulator with predefined route (highway):"
echo "  cd backend && node scripts/tracking-simulator.js --vehicle=TRUCK003 --route=highway_route"
echo ""
echo "Multiple simulators at once (Windows):"
echo "  cd backend"
echo "  start cmd /k \"node scripts/tracking-simulator.js --vehicle=TRUCK001\""
echo "  start cmd /k \"node scripts/tracking-simulator.js --vehicle=TRUCK002\""
echo "  start cmd /k \"node scripts/tracking-simulator.js --vehicle=TRUCK003\""
echo ""

# ============================================================================
# TESTING & VALIDATION
# ============================================================================
echo "═══════════════════════════════════════════════════════════════════════"
echo "STEP 3: TESTING & VALIDATION"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Run integration tests:"
echo "  cd backend && node test-live-tracking.js"
echo ""
echo "Verify backend is running:"
echo "  curl http://localhost:3000/health"
echo ""

# ============================================================================
# API CALLS
# ============================================================================
echo "═══════════════════════════════════════════════════════════════════════"
echo "STEP 4: API CALLS & TESTING"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Get all accident zones (heatmap):"
echo "  curl http://localhost:3000/api/v1/accidents/heatmap"
echo ""
echo "Get nearby zones for location:"
echo "  curl \"http://localhost:3000/api/v1/accidents/nearby-zones?lat=18.52&lng=73.85&radius=5000\""
echo ""
echo "Get vehicle alerts:"
echo "  curl http://localhost:3000/api/v1/accidents/vehicle/TRUCK001/alerts"
echo ""
echo "Get active alerts:"
echo "  curl http://localhost:3000/api/v1/accidents/active"
echo ""
echo "Get alert statistics:"
echo "  curl http://localhost:3000/api/v1/accidents/vehicle/TRUCK001/stats"
echo ""
echo "Acknowledge an alert (get alertId first):"
echo "  curl -X PATCH http://localhost:3000/api/v1/accidents/alerts/{ALERT_ID}/acknowledge \" \
echo "    -H \"Content-Type: application/json\" \" \
echo "    -d {\"acknowledgedBy\": \"driver-001\"}"
echo ""

# ============================================================================
# DATABASE QUERIES
# ============================================================================
echo "═══════════════════════════════════════════════════════════════════════"
echo "STEP 5: DATABASE QUERIES (MongoDB)"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Connect to MongoDB:"
echo "  mongosh mongodb://localhost:27017/logimetrics_db"
echo ""
echo "Check accident zones:"
echo "  db.accident_zones.find().pretty()"
echo "  db.accident_zones.countDocuments()"
echo ""
echo "Check live tracking data:"
echo "  db.live_tracking.find().limit(10).pretty()"
echo "  db.live_tracking.countDocuments()"
echo ""
echo "Check tracking alerts:"
echo "  db.live_tracking_alerts.find().pretty()"
echo "  db.live_tracking_alerts.countDocuments()"
echo ""
echo "Check alerts for specific vehicle:"
echo "  db.live_tracking_alerts.find({vehicleId: \"TRUCK001\"}).pretty()"
echo ""
echo "Check alerts by severity:"
echo "  db.live_tracking_alerts.find({severity: \"high\"}).count()"
echo "  db.live_tracking_alerts.find({severity: \"medium\"}).count()"
echo "  db.live_tracking_alerts.find({severity: \"low\"}).count()"
echo ""
echo "Get alert statistics:"
echo "  db.live_tracking_alerts.aggregate(["
echo "    {\\$group: {_id: \"\\$severity\", count: {\\$sum: 1}}}"
echo "  ])"
echo ""

# ============================================================================
# TROUBLESHOOTING
# ============================================================================
echo "═══════════════════════════════════════════════════════════════════════"
echo "TROUBLESHOOTING COMMANDS"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Check if backend is running:"
echo "  curl http://localhost:3000/health"
echo ""
echo "Check port 3000 is listening (Windows):"
echo "  netstat -ano | findstr :3000"
echo ""
echo "Kill process on port 3000 (Windows):"
echo "  taskkill /PID {PID} /F"
echo ""
echo "Check MongoDB is running:"
echo "  curl http://localhost:27017"
echo ""
echo "Check logs in backend:"
echo "  tail -f backend/logs/*.log  (Linux/Mac)"
echo "  Get-Content backend\\logs\\*.log -Tail 20 -Wait  (PowerShell)"
echo ""

# ============================================================================
# MONITORING & MANAGEMENT
# ============================================================================
echo "═══════════════════════════════════════════════════════════════════════"
echo "MONITORING & MANAGEMENT"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Monitor real-time alerts (use in separate terminal):"
echo "  cd backend && node scripts/tracking-simulator.js --vehicle=TEST001 --route=downtown_to_airport"
echo ""
echo "Check browser console (Chrome/Firefox DevTools):"
echo "  Press F12 → Console tab"
echo "  Filter: \"Location update:\" or \"ACCIDENT ZONE ALERT\""
echo ""
echo "Monitor database connections:"
echo "  mongosh"
echo "  use logimetrics_db"
echo "  db.serverStatus().connections"
echo ""

# ============================================================================
# QUICK REFERENCE
# ============================================================================
echo "═══════════════════════════════════════════════════════════════════════"
echo "QUICK REFERENCE"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "📊 Ports:"
echo "  Backend:  http://localhost:3000"
echo "  Frontend: http://localhost:5173"
echo "  MongoDB:  mongodb://localhost:27017"
echo ""
echo "🗺️  Map URL:"
echo "  http://localhost:5173/accidents"
echo ""
echo "🚗 Vehicle Types:"
echo "  TRUCK001, TRUCK002, etc. (or any custom name)"
echo ""
echo "📍 Prebuilt Routes:"
echo "  downtown_to_airport  (passes through high-accident area)"
echo "  airport_to_downtown"
echo "  highway_route"
echo ""
echo "⚠️  Alert Severity:"
echo "  🔴 HIGH:   <300m from zone, 10+ accidents"
echo "  🟡 MEDIUM: 300-600m, 5-9 accidents"
echo "  🟢 LOW:    600-1000m, <5 accidents"
echo ""
echo "📚 Documentation:"
echo "  LIVE_TRACKING_GUIDE.md           (comprehensive guide)"
echo "  LIVE_TRACKING_QUICK_REFERENCE.md (quick start)"
echo "  LIVE_TRACKING_SYSTEM_SUMMARY.md  (overview)"
echo ""
echo "================================"
echo "Happy Testing! 🚀"
echo "================================"
echo ""
